/**
 * Roteiro introdutório por ano escolar (1º ano do Fundamental ao 3º ano do Médio).
 * A sequência é aproximada: redes e escolas podem distribuir os temas em anos diferentes.
 * Cada item: "Tópico | explicação". Não substitui o currículo completo da escola.
 */

export const YEARS = [
  "1º EF", "2º EF", "3º EF", "4º EF", "5º EF", "6º EF", "7º EF", "8º EF", "9º EF",
  "1º EM", "2º EM", "3º EM",
] as const;
export type Year = (typeof YEARS)[number];

export const YEAR_LABEL: Record<Year, string> = {
  "1º EF": "1º ano – Fundamental", "2º EF": "2º ano – Fundamental", "3º EF": "3º ano – Fundamental",
  "4º EF": "4º ano – Fundamental", "5º EF": "5º ano – Fundamental", "6º EF": "6º ano – Fundamental",
  "7º EF": "7º ano – Fundamental", "8º EF": "8º ano – Fundamental", "9º EF": "9º ano – Fundamental",
  "1º EM": "1º ano – Ensino Médio", "2º EM": "2º ano – Ensino Médio", "3º EM": "3º ano – Ensino Médio",
};

type Topics = Partial<Record<Year, string[]>>;

export const curriculum: Record<string, Topics> = {
  matematica: {
    "1º EF": [
      "Contagem até 100 | Contar objetos, ler e escrever números e entender que cada número representa uma quantidade.",
      "Adição e subtração simples | Juntar (somar) e tirar (subtrair) quantidades pequenas usando objetos e desenhos.",
      "Formas geométricas | Reconhecer círculo, quadrado, triângulo e retângulo no dia a dia.",
      "Medidas do dia a dia | Comparar: maior/menor, mais alto/mais baixo, mais pesado/mais leve.",
    ],
    "2º EF": [
      "Números até 1000 | Unidade, dezena e centena: 245 = 2 centenas + 4 dezenas + 5 unidades.",
      "Adição e subtração com reagrupamento | O famoso \"vai um\" e \"empresta um\" nas contas armadas.",
      "Ideia de multiplicação | Somar parcelas iguais: 3 + 3 + 3 + 3 = 4 × 3 = 12.",
      "Dinheiro, tempo e calendário | Moedas e cédulas do real, horas no relógio, dias, semanas e meses.",
    ],
    "3º EF": [
      "Tabuada | Multiplicações de 1 a 10 e suas propriedades (a ordem não altera o resultado).",
      "Divisão | Repartir em partes iguais: 12 ÷ 3 = 4. O que sobra é o resto.",
      "Medidas | Metro e centímetro, quilo e grama, litro e mililitro.",
      "Figuras espaciais | Cubo, esfera, cilindro, cone e pirâmide: faces, arestas e vértices.",
    ],
    "4º EF": [
      "Números até a dezena de milhar | Leitura, escrita, composição e comparação de números grandes.",
      "Multiplicação e divisão com mais algarismos | Algoritmo da multiplicação e divisão por 1 algarismo.",
      "Frações simples | 1/2, 1/3, 1/4: parte de um inteiro dividido em partes iguais.",
      "Perímetro e área | Perímetro é o contorno; área é a superfície, contada em quadradinhos.",
    ],
    "5º EF": [
      "Números decimais | 0,5 = 5/10. Décimos, centésimos e milésimos; uso com dinheiro.",
      "Frações equivalentes e porcentagem | 1/2 = 2/4 = 50%. 25% é um quarto de algo.",
      "Operações com decimais | Somar e subtrair alinhando a vírgula.",
      "Gráficos e tabelas | Ler e montar gráficos de barras e de colunas.",
    ],
    "6º EF": [
      "Números naturais e sistema decimal | Valor posicional, ordens e classes.",
      "Múltiplos, divisores, MMC e MDC | Critérios de divisibilidade, números primos e fatoração.",
      "Frações e decimais | Operações com frações e conversão entre fração, decimal e porcentagem.",
      "Geometria plana | Ângulos, retas paralelas e perpendiculares, polígonos.",
    ],
    "7º EF": [
      "Números inteiros | Positivos e negativos, reta numérica e regra de sinais.",
      "Números racionais | Operações com frações e decimais positivos e negativos.",
      "Equações do 1º grau | ax + b = c: isolar o x fazendo a mesma operação dos dois lados.",
      "Razão, proporção e regra de três | a/b = c/d → a·d = b·c. Grandezas diretas e inversas.",
      "Ângulos e triângulos | A soma dos ângulos internos de um triângulo é 180°.",
    ],
    "8º EF": [
      "Potenciação e radiciação | Propriedades das potências, raiz quadrada e notação científica.",
      "Expressões algébricas e produtos notáveis | (a + b)² = a² + 2ab + b².",
      "Sistemas de equações do 1º grau | Métodos da substituição e da adição.",
      "Área de figuras planas | Quadrado, retângulo, triângulo, trapézio, losango e círculo (πr²).",
      "Estatística | Média, moda e mediana.",
    ],
    "9º EF": [
      "Números reais | Racionais e irracionais (√2, π).",
      "Equação do 2º grau | ax² + bx + c = 0; Δ = b² − 4ac; x = (−b ± √Δ)/2a.",
      "Funções | Ideia de função, função afim (y = ax + b) e gráficos.",
      "Teorema de Pitágoras e semelhança | a² = b² + c²; Teorema de Tales.",
      "Relações trigonométricas no triângulo retângulo | seno, cosseno e tangente.",
    ],
    "1º EM": [
      "Conjuntos | União, interseção, diferença e conjuntos numéricos.",
      "Função afim e quadrática | Gráficos, raízes, vértice (−b/2a, −Δ/4a) e estudo do sinal.",
      "Função exponencial e logarítmica | aˣ e logₐb = x ⇔ aˣ = b; propriedades dos logaritmos.",
      "Progressões | PA: aₙ = a₁ + (n−1)r. PG: aₙ = a₁·qⁿ⁻¹.",
      "Trigonometria no triângulo | Leis dos senos e dos cossenos.",
    ],
    "2º EM": [
      "Trigonometria no ciclo | Radianos, funções seno, cosseno e tangente.",
      "Matrizes e determinantes | Operações com matrizes, determinante 2×2 e 3×3 (Sarrus).",
      "Sistemas lineares | Escalonamento e regra de Cramer.",
      "Análise combinatória | Princípio fundamental da contagem, permutação, arranjo e combinação.",
      "Probabilidade | P = casos favoráveis / casos possíveis.",
      "Geometria espacial | Prismas, pirâmides, cilindros, cones e esferas: áreas e volumes.",
    ],
    "3º EM": [
      "Geometria analítica | Distância entre pontos, equação da reta e da circunferência.",
      "Números complexos | i² = −1; forma algébrica a + bi e operações.",
      "Polinômios e equações algébricas | Divisão de polinômios, Briot-Ruffini, relações de Girard.",
      "Estatística | Média, mediana, moda, variância e desvio padrão.",
      "Matemática financeira | Juros simples J = C·i·t e compostos M = C(1+i)ᵗ.",
      "Revisão ENEM | Interpretação de gráficos, proporcionalidade e porcentagem.",
    ],
  },

  portugues: {
    "1º EF": [
      "Alfabeto | Vogais e consoantes, letras maiúsculas e minúsculas.",
      "Sílabas | Juntar letras para formar sílabas e sílabas para formar palavras.",
      "Leitura de palavras e frases | Ler pequenos textos, parlendas e cantigas.",
      "Escrita do nome | Escrever o próprio nome e palavras do cotidiano.",
    ],
    "2º EF": [
      "Ortografia inicial | Uso de R/RR, S/SS, M antes de P e B.",
      "Frase e pontuação | Ponto final, interrogação e exclamação.",
      "Leitura e interpretação | Fábulas, bilhetes e contos curtos.",
      "Produção de textos curtos | Contar uma história com começo, meio e fim.",
    ],
    "3º EF": [
      "Substantivo e adjetivo | Substantivo nomeia; adjetivo caracteriza.",
      "Singular e plural, masculino e feminino | Flexões das palavras.",
      "Sinais gráficos | Acento agudo, circunflexo, til e cedilha.",
      "Gêneros textuais | Carta, receita, notícia e história em quadrinhos.",
    ],
    "4º EF": [
      "Verbos | Ação, estado ou fenômeno; tempos presente, passado e futuro.",
      "Pronomes pessoais | Eu, tu, ele, nós, vós, eles.",
      "Sílaba tônica | Oxítonas, paroxítonas e proparoxítonas.",
      "Paragrafação | Organizar ideias em parágrafos.",
    ],
    "5º EF": [
      "Classes de palavras | Artigo, numeral, advérbio, preposição e conjunção.",
      "Acentuação | Todas as proparoxítonas são acentuadas.",
      "Discurso direto e indireto | Uso do travessão e dos dois-pontos.",
      "Interpretação | Ideia principal, fato e opinião.",
    ],
    "6º EF": [
      "Variação linguística | Linguagem formal e informal; regionalismos.",
      "Fonologia | Fonema, letra, dígrafo, encontro vocálico e consonantal.",
      "Estrutura das palavras | Radical, prefixo e sufixo.",
      "Gêneros narrativos | Conto, crônica e lenda: narrador, personagens, tempo e espaço.",
    ],
    "7º EF": [
      "Frase, oração e período | Oração tem verbo; período pode ser simples ou composto.",
      "Sujeito e predicado | Tipos de sujeito: simples, composto, oculto, indeterminado e inexistente.",
      "Verbos: modos e tempos | Indicativo, subjuntivo e imperativo.",
      "Textos jornalísticos | Notícia, reportagem e entrevista.",
    ],
    "8º EF": [
      "Termos integrantes | Objeto direto, objeto indireto, complemento nominal e agente da passiva.",
      "Termos acessórios | Adjunto adnominal, adjunto adverbial e aposto; vocativo.",
      "Vozes verbais | Ativa, passiva e reflexiva.",
      "Textos argumentativos | Artigo de opinião: tese, argumentos e conclusão.",
    ],
    "9º EF": [
      "Período composto | Coordenação e subordinação.",
      "Orações subordinadas | Substantivas, adjetivas e adverbiais.",
      "Concordância e regência | Verbo concorda com o sujeito; verbos exigem preposições.",
      "Crase | Fusão de a + a: \"Vou à escola\".",
      "Figuras de linguagem | Metáfora, comparação, metonímia, ironia, hipérbole.",
    ],
    "1º EM": [
      "Literatura: Trovadorismo, Humanismo e Classicismo | Cantigas, Gil Vicente e Camões.",
      "Quinhentismo, Barroco e Arcadismo | Carta de Caminha, Gregório de Matos, Tomás A. Gonzaga.",
      "Morfologia completa | As 10 classes gramaticais.",
      "Funções da linguagem | Referencial, emotiva, conativa, fática, metalinguística e poética.",
    ],
    "2º EM": [
      "Romantismo | Poesia (Gonçalves Dias, Álvares de Azevedo, Castro Alves) e prosa (José de Alencar).",
      "Realismo e Naturalismo | Machado de Assis (Dom Casmurro) e Aluísio Azevedo (O Cortiço).",
      "Parnasianismo e Simbolismo | Olavo Bilac e Cruz e Sousa.",
      "Sintaxe | Análise do período simples e composto.",
    ],
    "3º EM": [
      "Pré-Modernismo e Modernismo | Semana de 22, Oswald e Mário de Andrade, Drummond, Graciliano.",
      "Literatura contemporânea | Clarice Lispector, Guimarães Rosa, João Cabral.",
      "Redação ENEM | Dissertativo-argumentativo: introdução, 2 desenvolvimentos e proposta de intervenção.",
      "Revisão gramatical | Concordância, regência, crase, pontuação e colocação pronominal.",
    ],
  },

  historia: {
    "1º EF": [
      "Minha história | Quem sou eu, minha família e minhas lembranças.",
      "Passado e presente | Como eram as brincadeiras e objetos antigamente.",
      "A escola | Regras de convivência e a história da escola.",
    ],
    "2º EF": [
      "Comunidade | O bairro e as pessoas que vivem nele.",
      "Tempo | Linha do tempo, calendário e medidas de tempo.",
      "Trabalho | Profissões de ontem e de hoje.",
    ],
    "3º EF": [
      "A cidade | Como as cidades surgem e se transformam.",
      "Patrimônio | Monumentos, festas e tradições locais.",
      "Espaços públicos e privados | Praças, ruas e casas.",
    ],
    "4º EF": [
      "Nomadismo e sedentarismo | Da caça e coleta à agricultura.",
      "Povos indígenas | Primeiros habitantes do Brasil e suas culturas.",
      "Migrações | Movimentos humanos ao longo do tempo.",
    ],
    "5º EF": [
      "Primeiras civilizações | Mesopotâmia, Egito e a escrita.",
      "Cidadania e direitos | Direitos humanos e o voto.",
      "Registros históricos | Fontes escritas, orais e materiais.",
    ],
    "6º EF": [
      "Pré-História | Paleolítico, Neolítico e Idade dos Metais.",
      "Antiguidade Oriental | Egito, Mesopotâmia, hebreus, fenícios e persas.",
      "Grécia Antiga | Esparta, Atenas e a democracia.",
      "Roma Antiga | Monarquia, República e Império.",
    ],
    "7º EF": [
      "Idade Média | Feudalismo, Igreja e Cruzadas.",
      "Renascimento e Reformas | Humanismo, Lutero e Contrarreforma.",
      "Grandes Navegações | Portugal e Espanha no mar.",
      "Brasil Colônia | Capitanias, açúcar e escravidão.",
    ],
    "8º EF": [
      "Iluminismo | Razão, Montesquieu, Rousseau e Voltaire.",
      "Revolução Francesa e Industrial | Liberdade, igualdade, fraternidade; máquinas a vapor.",
      "Independência do Brasil | 1822 e o Primeiro Reinado.",
      "Período Regencial e Segundo Reinado | Revoltas, café e abolição (1888).",
    ],
    "9º EF": [
      "República Velha | Café com leite, coronelismo e revoltas.",
      "Primeira e Segunda Guerra Mundial | Causas, alianças e consequências.",
      "Era Vargas | Estado Novo e leis trabalhistas.",
      "Guerra Fria e Ditadura Militar | EUA × URSS; Brasil de 1964 a 1985.",
      "Redemocratização | Constituição de 1988.",
    ],
    "1º EM": [
      "Introdução à História | Fontes, tempo histórico e historiografia.",
      "Antiguidade clássica aprofundada | Grécia e Roma: política, cultura e legado.",
      "Idade Média | Feudalismo, Império Bizantino e mundo islâmico.",
      "África e América pré-colonial | Reinos africanos, maias, astecas e incas.",
    ],
    "2º EM": [
      "Idade Moderna | Absolutismo, mercantilismo e colonização.",
      "Brasil Colônia e Império | Economia, sociedade e revoltas.",
      "Revoluções burguesas | Inglesa, Americana e Francesa.",
      "Imperialismo | Partilha da África e da Ásia.",
    ],
    "3º EM": [
      "Século XX | Guerras mundiais, Revolução Russa e crise de 1929.",
      "Brasil República | Da República Velha à Nova República.",
      "Guerra Fria e descolonização | Bipolaridade, Cuba, Vietnã.",
      "Mundo contemporâneo | Globalização e conflitos atuais.",
    ],
  },

  geografia: {
    "1º EF": [
      "Meu lugar | A casa, a escola e o caminho entre elas.",
      "Paisagem | Elementos naturais e construídos.",
      "Dia e noite | Rotinas e o movimento do Sol.",
    ],
    "2º EF": [
      "Orientação | Frente, atrás, direita, esquerda.",
      "Meios de transporte e comunicação | Como as pessoas se deslocam e se comunicam.",
      "Uso da água | Importância e cuidados.",
    ],
    "3º EF": [
      "Campo e cidade | Diferenças e relações entre eles.",
      "Mapas simples | Legenda e representação dos lugares.",
      "Recursos naturais | Solo, água e vegetação.",
    ],
    "4º EF": [
      "Pontos cardeais | Norte, Sul, Leste e Oeste.",
      "Município e estado | Organização territorial.",
      "Relevo e hidrografia | Montanhas, planaltos, planícies e rios.",
    ],
    "5º EF": [
      "Regiões do Brasil | Norte, Nordeste, Centro-Oeste, Sudeste e Sul.",
      "População brasileira | Diversidade e distribuição.",
      "Problemas ambientais | Poluição, desmatamento e reciclagem.",
    ],
    "6º EF": [
      "Planeta Terra | Movimentos de rotação e translação; estações do ano.",
      "Cartografia | Escala, coordenadas geográficas (latitude e longitude).",
      "Estrutura da Terra | Crosta, manto e núcleo; placas tectônicas.",
      "Clima e vegetação | Tempo × clima; biomas.",
    ],
    "7º EF": [
      "Território brasileiro | Formação e divisão regional.",
      "Biomas do Brasil | Amazônia, Cerrado, Caatinga, Mata Atlântica, Pampa e Pantanal.",
      "População do Brasil | Crescimento, migrações e urbanização.",
      "Economia brasileira | Agropecuária, indústria e serviços.",
    ],
    "8º EF": [
      "América | Aspectos físicos, população e economia.",
      "África | Diversidade, colonização e desafios atuais.",
      "Globalização | Blocos econômicos (Mercosul, Nafta/USMCA).",
      "Desenvolvimento | IDH e desigualdade.",
    ],
    "9º EF": [
      "Europa | Formação, União Europeia.",
      "Ásia | China, Japão, Índia e Oriente Médio.",
      "Oceania e regiões polares | Características gerais.",
      "Geopolítica mundial | Conflitos e ordem mundial.",
    ],
    "1º EM": [
      "Cartografia avançada | Projeções, fusos horários e sensoriamento remoto.",
      "Geologia e geomorfologia | Rochas, minerais e agentes do relevo.",
      "Climatologia | Massas de ar, fenômenos El Niño e La Niña.",
      "Hidrografia e biomas mundiais | Bacias hidrográficas e domínios morfoclimáticos.",
    ],
    "2º EM": [
      "População mundial | Transição demográfica, pirâmides etárias e migrações.",
      "Urbanização | Metrópoles, megalópoles e problemas urbanos.",
      "Industrialização | Revoluções industriais e fontes de energia.",
      "Agropecuária | Agronegócio, agricultura familiar e questão agrária.",
    ],
    "3º EM": [
      "Globalização e geopolítica | Nova ordem mundial, blocos e organismos internacionais.",
      "Conflitos mundiais | Oriente Médio, terrorismo e refugiados.",
      "Questões ambientais | Aquecimento global, acordos climáticos e sustentabilidade.",
      "Geografia do Brasil para o ENEM | Regionalização, economia e meio ambiente.",
    ],
  },

  ciencias: {
    "1º EF": [
      "Corpo humano | Partes do corpo e os cinco sentidos.",
      "Hábitos de higiene | Lavar as mãos, escovar os dentes e tomar banho.",
      "Materiais | Objetos feitos de plástico, madeira, metal e vidro.",
    ],
    "2º EF": [
      "Seres vivos | Plantas e animais: características e cuidados.",
      "Luz e som | Sol como fonte de luz e calor.",
      "Prevenção de acidentes | Cuidados em casa.",
    ],
    "3º EF": [
      "Animais | Vertebrados e invertebrados, alimentação e habitat.",
      "Som e luz | Como o som se propaga; sombras.",
      "Terra | Formato do planeta, solo e ar.",
    ],
    "4º EF": [
      "Cadeias alimentares | Produtores, consumidores e decompositores.",
      "Microrganismos | Fungos, bactérias e doenças.",
      "Misturas e transformações | Mudanças reversíveis e irreversíveis.",
    ],
    "5º EF": [
      "Sistemas do corpo | Digestório, respiratório e circulatório.",
      "Alimentação saudável | Nutrientes e pirâmide alimentar.",
      "Ciclo da água | Evaporação, condensação e precipitação.",
      "Astronomia | Constelações e fases da Lua.",
    ],
    "6º EF": [
      "Célula | Unidade básica da vida: membrana, citoplasma e núcleo.",
      "Níveis de organização | Célula → tecido → órgão → sistema → organismo.",
      "Sistema nervoso e visão | Neurônios e funcionamento dos olhos.",
      "Misturas | Homogêneas e heterogêneas; métodos de separação.",
    ],
    "7º EF": [
      "Máquinas simples | Alavancas, polias e plano inclinado.",
      "Calor e temperatura | Condução, convecção e irradiação.",
      "Ecossistemas | Biomas e impactos ambientais.",
      "Atmosfera | Composição do ar e efeito estufa.",
    ],
    "8º EF": [
      "Reprodução | Sistemas reprodutores, puberdade e métodos contraceptivos.",
      "Energia | Fontes renováveis e não renováveis; circuitos elétricos.",
      "Sistema Sol-Terra-Lua | Estações do ano, marés e eclipses.",
      "Clima | Fenômenos atmosféricos.",
    ],
    "9º EF": [
      "Matéria e átomo | Modelos atômicos, elementos e tabela periódica.",
      "Reações químicas | Reagentes e produtos; conservação da massa.",
      "Genética | DNA, genes e primeira lei de Mendel.",
      "Evolução | Darwin e seleção natural.",
      "Ondas e radiação | Luz, som e ondas eletromagnéticas.",
    ],
    "1º EM": [
      "Biologia: Citologia | Organelas, membrana plasmática, respiração celular e fotossíntese.",
      "Bioquímica | Carboidratos, lipídios, proteínas, vitaminas e ácidos nucleicos.",
      "Divisão celular | Mitose e meiose.",
      "Ecologia | Cadeias, teias, ciclos biogeoquímicos e relações ecológicas.",
    ],
    "2º EM": [
      "Classificação dos seres vivos | Vírus, bactérias, protozoários, fungos, plantas e animais.",
      "Botânica | Briófitas, pteridófitas, gimnospermas e angiospermas.",
      "Zoologia | Invertebrados e vertebrados.",
      "Fisiologia humana | Todos os sistemas do corpo humano.",
    ],
    "3º EM": [
      "Genética | Leis de Mendel, grupos sanguíneos, herança ligada ao sexo.",
      "Biotecnologia | Transgênicos, clonagem e DNA recombinante.",
      "Evolução | Lamarck, Darwin, neodarwinismo e especiação.",
      "Revisão ENEM de Biologia | Ecologia, saúde e meio ambiente.",
    ],
  },

  ingles: {
    "1º EF": ["Greetings | Hello, hi, goodbye, good morning.", "Colors | Red, blue, yellow, green.", "Numbers 1–10 | One, two, three..."],
    "2º EF": ["Family | Mother, father, brother, sister.", "Animals | Dog, cat, bird, fish.", "Numbers 1–20 | Eleven, twelve... twenty."],
    "3º EF": ["School objects | Pen, pencil, book, eraser.", "Body parts | Head, eyes, hands, feet.", "Toys and games | Ball, doll, kite."],
    "4º EF": ["Food | Apple, bread, milk, rice.", "Days of the week and months | Monday... January...", "Verb to be (I am, you are) | Frases simples de identificação."],
    "5º EF": ["Daily routine | Wake up, have breakfast, go to school.", "Weather and seasons | Sunny, rainy; summer, winter.", "Can / can't | Falar de habilidades: I can swim."],
    "6º EF": [
      "Verb to be | I am, you are, he/she/it is – afirmativa, negativa e interrogativa.",
      "Personal pronouns e possessive adjectives | I/my, you/your, he/his, she/her.",
      "There is / there are | Indicar existência: There is a book.",
      "Simple present | I play / She plays – rotina e hábitos.",
    ],
    "7º EF": [
      "Present continuous | I am studying now.",
      "Simple past | Verbos regulares (-ed) e irregulares (went, saw).",
      "Adjectives | Posição antes do substantivo: a big house.",
      "Countable / uncountable | Many, much, some, any.",
    ],
    "8º EF": [
      "Future | Will e going to.",
      "Comparatives e superlatives | Taller, the tallest; more beautiful.",
      "Past continuous | I was reading when...",
      "Modal verbs | Should, must, might.",
    ],
    "9º EF": [
      "Present perfect | I have lived here since 2010.",
      "Passive voice | The book was written by...",
      "Conditionals 0 e 1 | If it rains, I will stay home.",
      "Reading strategies | Skimming, scanning e cognatos.",
    ],
    "1º EM": ["Interpretação de textos | Cognatos, falsos cognatos e inferência.", "Tempos verbais revisados | Presente, passado e futuro.", "Pronouns e articles | Pronomes e artigos definidos/indefinidos."],
    "2º EM": ["Present perfect continuous e past perfect | Ações anteriores a outras no passado.", "Conditionals 2 e 3 | If I were you... / If I had known...", "Relative pronouns | Who, which, that, whose."],
    "3º EM": ["Reported speech | He said that he was tired.", "Phrasal verbs e linking words | Give up, however, although.", "Inglês no ENEM | Estratégias de leitura e questões comentadas."],
  },

  fisica: {
    "9º EF": [
      "Introdução à Física | Grandezas, unidades (SI) e medidas.",
      "Movimento | Velocidade média v = Δs/Δt.",
      "Força | Leis de Newton de forma introdutória.",
      "Energia | Cinética, potencial e conservação.",
    ],
    "1º EM": [
      "Cinemática | MU (s = s₀ + vt), MUV (v = v₀ + at; s = s₀ + v₀t + at²/2), Torricelli.",
      "Lançamentos e movimento circular | Queda livre, lançamento oblíquo, velocidade angular.",
      "Dinâmica | Leis de Newton: F = m·a; atrito, peso e força normal.",
      "Trabalho, energia e potência | τ = F·d; Ec = mv²/2; Ep = mgh; P = τ/Δt.",
      "Quantidade de movimento e gravitação | Q = m·v; Leis de Kepler; F = G·Mm/d².",
      "Hidrostática | Pressão, empuxo (Arquimedes) e princípio de Pascal.",
    ],
    "2º EM": [
      "Termologia | Escalas termométricas, dilatação e calorimetria Q = m·c·ΔT.",
      "Termodinâmica | Gases, 1ª e 2ª leis, máquinas térmicas.",
      "Óptica | Reflexão, refração, espelhos e lentes.",
      "Ondulatória | v = λ·f; som, ressonância e efeito Doppler.",
    ],
    "3º EM": [
      "Eletrostática | Carga, Lei de Coulomb, campo e potencial elétrico.",
      "Eletrodinâmica | Corrente, Lei de Ohm U = R·i, potência P = U·i, circuitos.",
      "Magnetismo e eletromagnetismo | Ímãs, campo magnético e indução (Faraday).",
      "Física Moderna | Relatividade, efeito fotoelétrico e física nuclear.",
    ],
  },

  quimica: {
    "9º EF": [
      "Matéria e seus estados | Sólido, líquido e gasoso; mudanças de estado.",
      "Átomo | Prótons, nêutrons e elétrons.",
      "Tabela periódica | Grupos, períodos e símbolos.",
      "Ligações e reações | Noções de ligações químicas e reações.",
    ],
    "1º EM": [
      "Matéria e substâncias | Substâncias puras, misturas e separação.",
      "Modelos atômicos | Dalton, Thomson, Rutherford e Bohr; distribuição eletrônica.",
      "Tabela periódica | Propriedades periódicas: raio, eletronegatividade, energia de ionização.",
      "Ligações químicas | Iônica, covalente e metálica; geometria e polaridade.",
      "Funções inorgânicas | Ácidos, bases, sais e óxidos.",
      "Estequiometria | Mol (6,02×10²³), massa molar e cálculos.",
    ],
    "2º EM": [
      "Soluções | Concentração C = m/V, molaridade e diluição.",
      "Propriedades coligativas | Ebulioscopia, crioscopia e osmose.",
      "Termoquímica | ΔH, reações exo e endotérmicas, Lei de Hess.",
      "Cinética química | Velocidade das reações e fatores que a alteram.",
      "Equilíbrio químico e pH | Kc, Le Chatelier; pH = −log[H⁺].",
      "Eletroquímica | Pilhas e eletrólise.",
    ],
    "3º EM": [
      "Química orgânica | O carbono, cadeias carbônicas e hidrocarbonetos.",
      "Funções orgânicas | Álcool, aldeído, cetona, ácido carboxílico, éster, amina e amida.",
      "Isomeria | Plana e espacial.",
      "Reações orgânicas e polímeros | Adição, substituição, combustão; plásticos.",
      "Química ambiental | Chuva ácida, efeito estufa e radioatividade.",
    ],
  },,

  astronomia: {
    "1º EF": ["Céu e observação | Reconheça Sol, Lua, estrelas e mudanças aparentes no céu.","Dia e noite | Relacione a observação do céu com a passagem do tempo."],
    "2º EF": ["Céu e observação | Reconheça Sol, Lua, estrelas e mudanças aparentes no céu.","Dia e noite | Relacione a observação do céu com a passagem do tempo."],
    "3º EF": ["Sistema Solar | Conheça Sol, planetas, Lua e pequenos corpos.","Eclipses e movimentos | Observe movimentos da Terra, Lua e fenômenos do céu."],
    "4º EF": ["Sistema Solar | Conheça Sol, planetas, Lua e pequenos corpos.","Eclipses e movimentos | Observe movimentos da Terra, Lua e fenômenos do céu."],
    "5º EF": ["Sistema Solar | Conheça Sol, planetas, Lua e pequenos corpos.","Eclipses e movimentos | Observe movimentos da Terra, Lua e fenômenos do céu."],
    "6º EF": ["Estrelas e galáxias | Estude como estrelas e galáxias são organizadas.","Exploração espacial | Conheça telescópios, sondas e missões espaciais."],
    "7º EF": ["Estrelas e galáxias | Estude como estrelas e galáxias são organizadas.","Exploração espacial | Conheça telescópios, sondas e missões espaciais."],
    "8º EF": ["Estrelas e galáxias | Estude como estrelas e galáxias são organizadas.","Exploração espacial | Conheça telescópios, sondas e missões espaciais."],
    "9º EF": ["Cosmologia | Estude expansão do Universo, exoplanetas e evidências astronômicas.","Astrofísica | Relacione luz, espectros, estrelas e gravitação."],
    "1º EM": ["Astronomia avançada | Estude mecânica celeste, evolução estelar e galáxias.","Astronomia no ENEM | Interprete gráficos, textos e situações de fenômenos astronômicos."],
    "2º EM": ["Astronomia avançada | Estude mecânica celeste, evolução estelar e galáxias.","Astronomia no ENEM | Interprete gráficos, textos e situações de fenômenos astronômicos."],
    "3º EM": ["Astronomia avançada | Estude mecânica celeste, evolução estelar e galáxias.","Astronomia no ENEM | Interprete gráficos, textos e situações de fenômenos astronômicos."],
  },

  sociologia: {
    "1º EF": ["Convivência e grupos | Observe regras, grupos, cooperação e diversidade.","Cultura | Reconheça costumes, valores e modos de viver."],
    "2º EF": ["Convivência e grupos | Observe regras, grupos, cooperação e diversidade.","Cultura | Reconheça costumes, valores e modos de viver."],
    "3º EF": ["Socialização | Entenda como aprendemos comportamentos e participamos de grupos.","Sociedade e trabalho | Observe como pessoas e atividades organizam a vida coletiva."],
    "4º EF": ["Socialização | Entenda como aprendemos comportamentos e participamos de grupos.","Sociedade e trabalho | Observe como pessoas e atividades organizam a vida coletiva."],
    "5º EF": ["Socialização | Entenda como aprendemos comportamentos e participamos de grupos.","Sociedade e trabalho | Observe como pessoas e atividades organizam a vida coletiva."],
    "6º EF": ["Instituições e desigualdade | Estude família, escola, trabalho, renda e oportunidades.","Mídia e cidadania | Analise comunicação, participação e relações sociais."],
    "7º EF": ["Instituições e desigualdade | Estude família, escola, trabalho, renda e oportunidades.","Mídia e cidadania | Analise comunicação, participação e relações sociais."],
    "8º EF": ["Instituições e desigualdade | Estude família, escola, trabalho, renda e oportunidades.","Mídia e cidadania | Analise comunicação, participação e relações sociais."],
    "9º EF": ["Poder e sociedade | Estude Estado, cidadania, desigualdade e movimentos sociais.","Globalização | Analise mudanças sociais, trabalho e mídias digitais."],
    "1º EM": ["Teorias sociológicas | Conheça conceitos de Durkheim, Marx e Weber.","Sociologia no ENEM | Interprete textos, dados e situações sociais."],
    "2º EM": ["Teorias sociológicas | Conheça conceitos de Durkheim, Marx e Weber.","Sociologia no ENEM | Interprete textos, dados e situações sociais."],
    "3º EM": ["Teorias sociológicas | Conheça conceitos de Durkheim, Marx e Weber.","Sociologia no ENEM | Interprete textos, dados e situações sociais."],
  },

  oratoria: {
    "1º EF": ["Comunicação básica | Fale com clareza, escute e organize ideias simples.","Apresentação | Pratique voz, postura e pequenas falas."],
    "2º EF": ["Comunicação básica | Fale com clareza, escute e organize ideias simples.","Apresentação | Pratique voz, postura e pequenas falas."],
    "3º EF": ["Histórias e sequência | Organize começo, desenvolvimento e conclusão.","Leitura oral | Trabalhe ritmo, pausas, volume e expressão."],
    "4º EF": ["Histórias e sequência | Organize começo, desenvolvimento e conclusão.","Leitura oral | Trabalhe ritmo, pausas, volume e expressão."],
    "5º EF": ["Histórias e sequência | Organize começo, desenvolvimento e conclusão.","Leitura oral | Trabalhe ritmo, pausas, volume e expressão."],
    "6º EF": ["Estrutura do discurso | Planeje introdução, desenvolvimento e encerramento.","Linguagem corporal | Pratique postura, olhar, gestos e entonação."],
    "7º EF": ["Estrutura do discurso | Planeje introdução, desenvolvimento e encerramento.","Linguagem corporal | Pratique postura, olhar, gestos e entonação."],
    "8º EF": ["Estrutura do discurso | Planeje introdução, desenvolvimento e encerramento.","Linguagem corporal | Pratique postura, olhar, gestos e entonação."],
    "9º EF": ["Argumentação e debate | Defenda ideias com razões e exemplos.","Seminários | Organize pesquisa, slides, tempo e respostas."],
    "1º EM": ["Oratória avançada | Trabalhe evidências, contrapontos, entrevistas e apresentações.","Comunicação profissional | Pratique pitch, debates e apresentações estruturadas."],
    "2º EM": ["Oratória avançada | Trabalhe evidências, contrapontos, entrevistas e apresentações.","Comunicação profissional | Pratique pitch, debates e apresentações estruturadas."],
    "3º EM": ["Oratória avançada | Trabalhe evidências, contrapontos, entrevistas e apresentações.","Comunicação profissional | Pratique pitch, debates e apresentações estruturadas."],
  },

  filosofia: {
    "1º EF": ["Perguntas e diálogo | Reflita sobre escolhas, regras, justiça e convivência.","Argumentação | Aprenda a explicar ideias e ouvir posições diferentes."],
    "2º EF": ["Perguntas e diálogo | Reflita sobre escolhas, regras, justiça e convivência.","Argumentação | Aprenda a explicar ideias e ouvir posições diferentes."],
    "3º EF": ["Ética e conhecimento | Analise valores, escolhas e como sabemos algo.","Filosofia antiga | Conheça problemas e ideias de Sócrates, Platão e Aristóteles."],
    "4º EF": ["Ética e conhecimento | Analise valores, escolhas e como sabemos algo.","Filosofia antiga | Conheça problemas e ideias de Sócrates, Platão e Aristóteles."],
    "5º EF": ["Ética e conhecimento | Analise valores, escolhas e como sabemos algo.","Filosofia antiga | Conheça problemas e ideias de Sócrates, Platão e Aristóteles."],
    "6º EF": ["Conhecimento e política | Compare razão, experiência, liberdade, justiça e Estado.","Ética aplicada | Analise dilemas e consequências de decisões."],
    "7º EF": ["Conhecimento e política | Compare razão, experiência, liberdade, justiça e Estado.","Ética aplicada | Analise dilemas e consequências de decisões."],
    "8º EF": ["Conhecimento e política | Compare razão, experiência, liberdade, justiça e Estado.","Ética aplicada | Analise dilemas e consequências de decisões."],
    "9º EF": ["Filosofia contemporânea | Estude ciência, existência, linguagem e ética aplicada.","Argumentação crítica | Analise teses, razões, evidências e conclusões."],
    "1º EM": ["Epistemologia e ética | Compare teorias e problemas filosóficos.","Filosofia no ENEM | Interprete textos, conceitos e argumentos."],
    "2º EM": ["Epistemologia e ética | Compare teorias e problemas filosóficos.","Filosofia no ENEM | Interprete textos, conceitos e argumentos."],
    "3º EM": ["Epistemologia e ética | Compare teorias e problemas filosóficos.","Filosofia no ENEM | Interprete textos, conceitos e argumentos."],
  },

  biologia: {
    "1º EF": ["Seres vivos | Observe plantas, animais, células e diversidade da vida.","Ambiente | Relacione seres vivos aos lugares onde vivem."],
    "2º EF": ["Seres vivos | Observe plantas, animais, células e diversidade da vida.","Ambiente | Relacione seres vivos aos lugares onde vivem."],
    "3º EF": ["Classificação | Conheça grupos de seres vivos e características observáveis.","Ecologia | Estude cadeias alimentares e relações com o ambiente."],
    "4º EF": ["Classificação | Conheça grupos de seres vivos e características observáveis.","Ecologia | Estude cadeias alimentares e relações com o ambiente."],
    "5º EF": ["Classificação | Conheça grupos de seres vivos e características observáveis.","Ecologia | Estude cadeias alimentares e relações com o ambiente."],
    "6º EF": ["Células e tecidos | Entenda níveis de organização dos seres vivos.","Ecologia e evolução | Estude relações ecológicas, adaptação e diversidade."],
    "7º EF": ["Células e tecidos | Entenda níveis de organização dos seres vivos.","Ecologia e evolução | Estude relações ecológicas, adaptação e diversidade."],
    "8º EF": ["Células e tecidos | Entenda níveis de organização dos seres vivos.","Ecologia e evolução | Estude relações ecológicas, adaptação e diversidade."],
    "9º EF": ["Genética e evolução | Estude DNA, hereditariedade, seleção natural e biotecnologia.","Fisiologia | Conheça sistemas do corpo e integração do organismo."],
    "1º EM": ["Biologia avançada | Genética, evolução, fisiologia, ecologia e biotecnologia.","Biologia no ENEM | Integre saúde, ambiente, genética e evolução."],
    "2º EM": ["Biologia avançada | Genética, evolução, fisiologia, ecologia e biotecnologia.","Biologia no ENEM | Integre saúde, ambiente, genética e evolução."],
    "3º EM": ["Biologia avançada | Genética, evolução, fisiologia, ecologia e biotecnologia.","Biologia no ENEM | Integre saúde, ambiente, genética e evolução."],
  },

  ensino-religioso: {
    "1º EF": ["Diversidade e respeito | Reconheça diferentes crenças, convicções e culturas.","Símbolos e celebrações | Conheça manifestações culturais e religiosas."],
    "2º EF": ["Diversidade e respeito | Reconheça diferentes crenças, convicções e culturas.","Símbolos e celebrações | Conheça manifestações culturais e religiosas."],
    "3º EF": ["Tradições e cultura | Observe ritos, festas, costumes e formas de transmissão.","Convivência | Pratique diálogo e respeito às diferenças."],
    "4º EF": ["Tradições e cultura | Observe ritos, festas, costumes e formas de transmissão.","Convivência | Pratique diálogo e respeito às diferenças."],
    "5º EF": ["Tradições e cultura | Observe ritos, festas, costumes e formas de transmissão.","Convivência | Pratique diálogo e respeito às diferenças."],
    "6º EF": ["Fenômeno religioso | Estude religião como dimensão cultural e social.","Diversidade no Brasil | Conheça pluralidade religiosa e combate à intolerância."],
    "7º EF": ["Fenômeno religioso | Estude religião como dimensão cultural e social.","Diversidade no Brasil | Conheça pluralidade religiosa e combate à intolerância."],
    "8º EF": ["Fenômeno religioso | Estude religião como dimensão cultural e social.","Diversidade no Brasil | Conheça pluralidade religiosa e combate à intolerância."],
    "9º EF": ["Laicidade e direitos | Relacione liberdade religiosa, cidadania e direitos.","Pluralismo | Analise relações entre religião, cultura e sociedade."],
    "1º EM": ["Estudos da religião | Compare abordagens históricas, culturais e sociais.","Revisão | Interprete textos sobre diversidade, laicidade e liberdade de consciência."],
    "2º EM": ["Estudos da religião | Compare abordagens históricas, culturais e sociais.","Revisão | Interprete textos sobre diversidade, laicidade e liberdade de consciência."],
    "3º EM": ["Estudos da religião | Compare abordagens históricas, culturais e sociais.","Revisão | Interprete textos sobre diversidade, laicidade e liberdade de consciência."],
  },

  redacao: {
    "1º EF": ["Escrita básica | Produza frases, pequenos textos, descrições e narrativas.","Revisão inicial | Trabalhe ortografia, pontuação e clareza."],
    "2º EF": ["Escrita básica | Produza frases, pequenos textos, descrições e narrativas.","Revisão inicial | Trabalhe ortografia, pontuação e clareza."],
    "3º EF": ["Gêneros textuais | Produza relatos, cartas, notícias e textos de opinião.","Parágrafos | Organize uma ideia principal com começo e desenvolvimento."],
    "4º EF": ["Gêneros textuais | Produza relatos, cartas, notícias e textos de opinião.","Parágrafos | Organize uma ideia principal com começo e desenvolvimento."],
    "5º EF": ["Gêneros textuais | Produza relatos, cartas, notícias e textos de opinião.","Parágrafos | Organize uma ideia principal com começo e desenvolvimento."],
    "6º EF": ["Texto argumentativo | Desenvolva tese, argumentos, exemplos e conclusão.","Coesão | Use conectivos e pronomes para ligar ideias."],
    "7º EF": ["Texto argumentativo | Desenvolva tese, argumentos, exemplos e conclusão.","Coesão | Use conectivos e pronomes para ligar ideias."],
    "8º EF": ["Texto argumentativo | Desenvolva tese, argumentos, exemplos e conclusão.","Coesão | Use conectivos e pronomes para ligar ideias."],
    "9º EF": ["Dissertação | Estruture introdução, desenvolvimento e conclusão.","Repertório | Use informações pertinentes para sustentar argumentos."],
    "1º EM": ["Redação ENEM | Planeje projeto de texto, argumentação e proposta de intervenção.","Revisão final | Aprimore conteúdo, coesão, coerência e norma-padrão."],
    "2º EM": ["Redação ENEM | Planeje projeto de texto, argumentação e proposta de intervenção.","Revisão final | Aprimore conteúdo, coesão, coerência e norma-padrão."],
    "3º EM": ["Redação ENEM | Planeje projeto de texto, argumentação e proposta de intervenção.","Revisão final | Aprimore conteúdo, coesão, coerência e norma-padrão."],
  },

  literatura: {
    "1º EF": ["Histórias e poemas | Conheça contos, fábulas, narrativas e poesias.","Elementos narrativos | Identifique personagens, narrador, tempo e espaço."],
    "2º EF": ["Histórias e poemas | Conheça contos, fábulas, narrativas e poesias.","Elementos narrativos | Identifique personagens, narrador, tempo e espaço."],
    "3º EF": ["Gêneros literários | Compare narrativa, poesia e teatro.","Linguagem figurada | Reconheça metáfora, comparação e outros recursos."],
    "4º EF": ["Gêneros literários | Compare narrativa, poesia e teatro.","Linguagem figurada | Reconheça metáfora, comparação e outros recursos."],
    "5º EF": ["Gêneros literários | Compare narrativa, poesia e teatro.","Linguagem figurada | Reconheça metáfora, comparação e outros recursos."],
    "6º EF": ["Literatura e sociedade | Relacione obras a contextos históricos e culturais.","Poesia e narrativa | Analise forma, enredo, foco narrativo e efeitos de sentido."],
    "7º EF": ["Literatura e sociedade | Relacione obras a contextos históricos e culturais.","Poesia e narrativa | Analise forma, enredo, foco narrativo e efeitos de sentido."],
    "8º EF": ["Literatura e sociedade | Relacione obras a contextos históricos e culturais.","Poesia e narrativa | Analise forma, enredo, foco narrativo e efeitos de sentido."],
    "9º EF": ["Modernismo | Conheça vanguardas, Semana de 1922 e literatura contemporânea.","Interpretação | Relacione linguagem, contexto, tema e ponto de vista."],
    "1º EM": ["Escolas literárias | Estude períodos, autores, obras e características.","Literatura no ENEM | Interprete textos relacionando forma, linguagem e contexto."],
    "2º EM": ["Escolas literárias | Estude períodos, autores, obras e características.","Literatura no ENEM | Interprete textos relacionando forma, linguagem e contexto."],
    "3º EM": ["Escolas literárias | Estude períodos, autores, obras e características.","Literatura no ENEM | Interprete textos relacionando forma, linguagem e contexto."],
  },

  geopolitica: {
    "1º EF": ["Território e comunidade | Observe limites, espaços e relações entre lugares.","Cooperação | Conheça formas simples de interação entre comunidades e países."],
    "2º EF": ["Território e comunidade | Observe limites, espaços e relações entre lugares.","Cooperação | Conheça formas simples de interação entre comunidades e países."],
    "3º EF": ["Países e território | Diferencie país, estado, município e fronteira.","Economia e circulação | Observe deslocamento de pessoas, mercadorias e informações."],
    "4º EF": ["Países e território | Diferencie país, estado, município e fronteira.","Economia e circulação | Observe deslocamento de pessoas, mercadorias e informações."],
    "5º EF": ["Países e território | Diferencie país, estado, município e fronteira.","Economia e circulação | Observe deslocamento de pessoas, mercadorias e informações."],
    "6º EF": ["Território e poder | Estude fronteiras, Estados, recursos e organizações.","Globalização | Analise relações econômicas e culturais entre países."],
    "7º EF": ["Território e poder | Estude fronteiras, Estados, recursos e organizações.","Globalização | Analise relações econômicas e culturais entre países."],
    "8º EF": ["Território e poder | Estude fronteiras, Estados, recursos e organizações.","Globalização | Analise relações econômicas e culturais entre países."],
    "9º EF": ["Ordem mundial | Estude conflitos, migrações, energia e distribuição de poder.","Organizações internacionais | Conheça ONU, blocos e acordos."],
    "1º EM": ["Geopolítica contemporânea | Analise globalização, conflitos, energia e relações internacionais.","Geopolítica no ENEM | Interprete mapas, gráficos, textos e atualidades com contexto."],
    "2º EM": ["Geopolítica contemporânea | Analise globalização, conflitos, energia e relações internacionais.","Geopolítica no ENEM | Interprete mapas, gráficos, textos e atualidades com contexto."],
    "3º EM": ["Geopolítica contemporânea | Analise globalização, conflitos, energia e relações internacionais.","Geopolítica no ENEM | Interprete mapas, gráficos, textos e atualidades com contexto."],
  },

  empreendedorismo: {
    "1º EF": ["Criatividade e ideias | Identifique problemas e pense em soluções.","Planejamento | Organize materiais, tarefas e etapas."],
    "2º EF": ["Criatividade e ideias | Identifique problemas e pense em soluções.","Planejamento | Organize materiais, tarefas e etapas."],
    "3º EF": ["Projetos | Defina problema, público, recursos e resultado esperado.","Finanças simples | Diferencie custos, receitas e orçamento."],
    "4º EF": ["Projetos | Defina problema, público, recursos e resultado esperado.","Finanças simples | Diferencie custos, receitas e orçamento."],
    "5º EF": ["Projetos | Defina problema, público, recursos e resultado esperado.","Finanças simples | Diferencie custos, receitas e orçamento."],
    "6º EF": ["Modelo de projeto | Estude proposta de valor, público, recursos e comunicação.","Marketing básico | Aprenda a apresentar uma solução ao público."],
    "7º EF": ["Modelo de projeto | Estude proposta de valor, público, recursos e comunicação.","Marketing básico | Aprenda a apresentar uma solução ao público."],
    "8º EF": ["Modelo de projeto | Estude proposta de valor, público, recursos e comunicação.","Marketing básico | Aprenda a apresentar uma solução ao público."],
    "9º EF": ["Validação e planejamento | Teste ideias, acompanhe resultados e considere riscos.","Responsabilidade | Analise impactos sociais, ambientais e financeiros."],
    "1º EM": ["Empreendedorismo avançado | Planejamento estratégico, marketing, inovação e finanças.","Projeto final | Desenvolva e apresente uma proposta de forma estruturada."],
    "2º EM": ["Empreendedorismo avançado | Planejamento estratégico, marketing, inovação e finanças.","Projeto final | Desenvolva e apresente uma proposta de forma estruturada."],
    "3º EM": ["Empreendedorismo avançado | Planejamento estratégico, marketing, inovação e finanças.","Projeto final | Desenvolva e apresente uma proposta de forma estruturada."],
  },

  historia-da-arte: {
    "1º EF": ["Arte e cultura | Observe cores, formas, desenhos, música e manifestações culturais.","Criação artística | Experimente diferentes materiais e linguagens."],
    "2º EF": ["Arte e cultura | Observe cores, formas, desenhos, música e manifestações culturais.","Criação artística | Experimente diferentes materiais e linguagens."],
    "3º EF": ["Antiguidade e patrimônio | Conheça arte egípcia, grega, romana e manifestações culturais.","Renascimento | Observe perspectiva, proporção e novas técnicas."],
    "4º EF": ["Antiguidade e patrimônio | Conheça arte egípcia, grega, romana e manifestações culturais.","Renascimento | Observe perspectiva, proporção e novas técnicas."],
    "5º EF": ["Antiguidade e patrimônio | Conheça arte egípcia, grega, romana e manifestações culturais.","Renascimento | Observe perspectiva, proporção e novas técnicas."],
    "6º EF": ["Barroco ao Realismo | Compare estilos, temas e contextos históricos.","Arte brasileira | Conheça transformações e patrimônio cultural."],
    "7º EF": ["Barroco ao Realismo | Compare estilos, temas e contextos históricos.","Arte brasileira | Conheça transformações e patrimônio cultural."],
    "8º EF": ["Barroco ao Realismo | Compare estilos, temas e contextos históricos.","Arte brasileira | Conheça transformações e patrimônio cultural."],
    "9º EF": ["Modernismo e vanguardas | Estude Impressionismo, vanguardas e Semana de 1922.","Arte contemporânea | Explore novas linguagens e tecnologias."],
    "1º EM": ["História da arte | Organize períodos, movimentos, obras e contextos.","Arte no ENEM | Interprete imagens, textos, técnicas e relações culturais."],
    "2º EM": ["História da arte | Organize períodos, movimentos, obras e contextos.","Arte no ENEM | Interprete imagens, textos, técnicas e relações culturais."],
    "3º EM": ["História da arte | Organize períodos, movimentos, obras e contextos.","Arte no ENEM | Interprete imagens, textos, técnicas e relações culturais."],
  },

  ecologia-e-educacao-ambiental: {
    "1º EF": ["Natureza e cuidado | Observe seres vivos, água, solo e resíduos.","Consumo consciente | Aprenda atitudes de cuidado e redução de desperdício."],
    "2º EF": ["Natureza e cuidado | Observe seres vivos, água, solo e resíduos.","Consumo consciente | Aprenda atitudes de cuidado e redução de desperdício."],
    "3º EF": ["Ecossistemas | Relacione seres vivos e fatores do ambiente.","Cadeias alimentares | Entenda produtores, consumidores e decompositores."],
    "4º EF": ["Ecossistemas | Relacione seres vivos e fatores do ambiente.","Cadeias alimentares | Entenda produtores, consumidores e decompositores."],
    "5º EF": ["Ecossistemas | Relacione seres vivos e fatores do ambiente.","Cadeias alimentares | Entenda produtores, consumidores e decompositores."],
    "6º EF": ["Biodiversidade | Estude biomas, relações ecológicas e conservação.","Impactos ambientais | Analise poluição, desmatamento e perda de habitat."],
    "7º EF": ["Biodiversidade | Estude biomas, relações ecológicas e conservação.","Impactos ambientais | Analise poluição, desmatamento e perda de habitat."],
    "8º EF": ["Biodiversidade | Estude biomas, relações ecológicas e conservação.","Impactos ambientais | Analise poluição, desmatamento e perda de habitat."],
    "9º EF": ["Mudanças ambientais | Estude clima, recursos naturais, resíduos e sustentabilidade.","Educação ambiental | Relacione problemas ambientais a ações responsáveis."],
    "1º EM": ["Ecologia avançada | Dinâmica de populações, ciclos, biodiversidade e conservação.","Questões ambientais no ENEM | Interprete gráficos, mapas e textos."],
    "2º EM": ["Ecologia avançada | Dinâmica de populações, ciclos, biodiversidade e conservação.","Questões ambientais no ENEM | Interprete gráficos, mapas e textos."],
    "3º EM": ["Ecologia avançada | Dinâmica de populações, ciclos, biodiversidade e conservação.","Questões ambientais no ENEM | Interprete gráficos, mapas e textos."],
  },

  algebra: {
    "1º EF": ["Padrões e igualdade | Reconheça sequências, relações e valores desconhecidos.","Problemas | Use números e símbolos para representar situações."],
    "2º EF": ["Padrões e igualdade | Reconheça sequências, relações e valores desconhecidos.","Problemas | Use números e símbolos para representar situações."],
    "3º EF": ["Expressões | Use letras para representar valores e relações.","Equações simples | Encontre valores desconhecidos em igualdades."],
    "4º EF": ["Expressões | Use letras para representar valores e relações.","Equações simples | Encontre valores desconhecidos em igualdades."],
    "5º EF": ["Expressões | Use letras para representar valores e relações.","Equações simples | Encontre valores desconhecidos em igualdades."],
    "6º EF": ["Equações e sistemas | Resolva equações do 1º grau e sistemas.","Produtos e fatoração | Simplifique e transforme expressões algébricas."],
    "7º EF": ["Equações e sistemas | Resolva equações do 1º grau e sistemas.","Produtos e fatoração | Simplifique e transforme expressões algébricas."],
    "8º EF": ["Equações e sistemas | Resolva equações do 1º grau e sistemas.","Produtos e fatoração | Simplifique e transforme expressões algébricas."],
    "9º EF": ["Equação do 2º grau | Resolva por fatoração e fórmula de Bhaskara.","Funções | Relacione variáveis e represente relações em gráficos."],
    "1º EM": ["Funções e álgebra | Estude exponenciais, logaritmos, progressões e sistemas.","Álgebra no ENEM | Modele problemas e interprete expressões e gráficos."],
    "2º EM": ["Funções e álgebra | Estude exponenciais, logaritmos, progressões e sistemas.","Álgebra no ENEM | Modele problemas e interprete expressões e gráficos."],
    "3º EM": ["Funções e álgebra | Estude exponenciais, logaritmos, progressões e sistemas.","Álgebra no ENEM | Modele problemas e interprete expressões e gráficos."],
  },

  geometria: {
    "1º EF": ["Formas e medidas | Reconheça figuras, posições, comprimentos e tamanhos.","Construções | Monte e compare formas simples."],
    "2º EF": ["Formas e medidas | Reconheça figuras, posições, comprimentos e tamanhos.","Construções | Monte e compare formas simples."],
    "3º EF": ["Perímetro e área | Calcule contornos e superfícies.","Ângulos e polígonos | Reconheça propriedades de figuras planas."],
    "4º EF": ["Perímetro e área | Calcule contornos e superfícies.","Ângulos e polígonos | Reconheça propriedades de figuras planas."],
    "5º EF": ["Perímetro e área | Calcule contornos e superfícies.","Ângulos e polígonos | Reconheça propriedades de figuras planas."],
    "6º EF": ["Triângulos e quadriláteros | Estude propriedades e relações angulares.","Circunferência | Conheça raio, diâmetro, comprimento e área."],
    "7º EF": ["Triângulos e quadriláteros | Estude propriedades e relações angulares.","Circunferência | Conheça raio, diâmetro, comprimento e área."],
    "8º EF": ["Triângulos e quadriláteros | Estude propriedades e relações angulares.","Circunferência | Conheça raio, diâmetro, comprimento e área."],
    "9º EF": ["Pitágoras e semelhança | Resolva problemas com relações métricas.","Geometria espacial | Estude sólidos, áreas e volumes."],
    "1º EM": ["Geometria avançada | Analítica, trigonometria, cônicas e sólidos.","Geometria no ENEM | Trabalhe escalas, mapas, áreas, volumes e interpretação."],
    "2º EM": ["Geometria avançada | Analítica, trigonometria, cônicas e sólidos.","Geometria no ENEM | Trabalhe escalas, mapas, áreas, volumes e interpretação."],
    "3º EM": ["Geometria avançada | Analítica, trigonometria, cônicas e sólidos.","Geometria no ENEM | Trabalhe escalas, mapas, áreas, volumes e interpretação."],
  },
};

export function parseTopic(t: string) {
  const [title, text] = t.split(" | ");
  return { title: title ?? t, text: text ?? "" };
}
