export const qOratoria = [
{q:"Qual é um dos principais objetivos da oratória?",options:["Confundir o público","Comunicar ideias de forma clara e adequada ao público","Falar o mais rápido possível","Evitar preparação"],answer:1,level:"facil",explanation:"A oratória busca tornar a comunicação oral clara, organizada e adequada ao público. Uma boa apresentação depende de conteúdo, estrutura, voz e interação."},
{q:"Qual estrutura básica organiza uma apresentação?",options:["Introdução, desenvolvimento e conclusão","Somente conclusão","Somente exemplos","Apenas perguntas"],answer:0,level:"facil",explanation:"A introdução apresenta o tema, o desenvolvimento explica e sustenta as ideias e a conclusão retoma a mensagem principal. Essa sequência ajuda o público a acompanhar o raciocínio."},
{q:"Por que a entonação é importante?",options:["Porque substitui o conteúdo","Porque destaca ideias e transmite intenção","Porque elimina a clareza","Porque deve ser sempre igual"],answer:1,level:"medio",explanation:"A entonação ajuda a transmitir destaque e intenção. Variações naturais da voz evitam uma fala monótona e podem facilitar a compreensão."},
{q:"O que é contato visual?",options:["Olhar para o chão","Direcionar o olhar naturalmente ao público","Olhar somente para uma pessoa","Nunca olhar para o público"],answer:1,level:"medio",explanation:"O contato visual ajuda a criar conexão e perceber a reação do público. Deve ser natural e distribuído, sem ficar fixo em uma única pessoa."},
{q:"Qual atitude ajuda ao responder perguntas?",options:["Interromper","Ouvir até o fim e responder objetivamente","Inventar","Evitar perguntas"],answer:1,level:"medio",explanation:"Ouvir a pergunta inteira ajuda a entender exatamente o que foi solicitado. Uma resposta objetiva e baseada no que você sabe é mais confiável."},
{q:"O que é ritmo de fala?",options:["Velocidade e variação da fala","Tamanho do palco","Quantidade de slides","Volume do microfone"],answer:0,level:"dificil",explanation:"Ritmo é a velocidade e organização temporal da fala. Pausas e variações adequadas dão tempo para o público processar informações."},
{q:"Por que ensaiar é útil?",options:["Para decorar cada palavra","Para testar tempo, clareza, ordem e dificuldades","Para impedir improviso","Para não conhecer o tema"],answer:1,level:"medio",explanation:"Ensaiar permite perceber partes confusas, ajustar o tempo e melhorar a sequência das ideias. O objetivo é dominar o conteúdo, não decorar cada frase."},
{q:"O que torna um argumento mais consistente?",options:["Gritar","Apresentar razões e evidências pertinentes","Usar palavras difíceis","Falar sem exemplos"],answer:1,level:"dificil",explanation:"Um argumento consistente apresenta uma ideia apoiada por razões e evidências relevantes. Clareza e relação direta com o tema ajudam o público a avaliar a mensagem."},
{q:"Qual postura ajuda na comunicação?",options:["Postura estável e natural","Esconder o corpo","Mover-se sem relação com a fala","Virar as costas"],answer:0,level:"dificil",explanation:"Uma postura estável e natural ajuda na projeção da voz e demonstra atenção. Gestos podem complementar a mensagem quando usados de forma coerente."},
{q:"O que fazer quando não souber uma resposta?",options:["Inventar","Admitir a dúvida e indicar como verificar","Ignorar","Mudar de assunto"],answer:1,level:"dificil",explanation:"Reconhecer uma dúvida é mais confiável do que inventar uma resposta. Se possível, explique que precisa verificar o dado e consulte uma fonte adequada."}
];