export const quizAstronomia = [
{q:"Qual e a estrela central do Sistema Solar?",options:["Lua","Sol","Sirius","Terra"],answer:1,level:"facil",explanation:"O Sol e a estrela central do Sistema Solar. Sua gravidade mantém os planetas em órbita e sua energia sustenta processos fundamentais na Terra."},
{q:"Qual movimento da Terra produz dias e noites?",options:["Translação","Rotação","Precessão","Revolução lunar"],answer:1,level:"facil",explanation:"A rotação é o giro da Terra em torno do próprio eixo. Esse movimento faz diferentes regiões alternarem entre iluminação e escuridão."},
{q:"Qual é o maior planeta do Sistema Solar?",options:["Terra","Marte","Júpiter","Netuno"],answer:2,level:"medio",explanation:"Júpiter é o maior planeta do Sistema Solar em massa e diâmetro. É um gigante gasoso com atmosfera extensa e muitos satélites."},
{q:"O que é uma galáxia?",options:["Um planeta","Um conjunto de estrelas, gás, poeira e outros objetos ligados pela gravidade","Uma camada da atmosfera","Um cometa"],answer:1,level:"medio",explanation:"Uma galáxia é uma grande estrutura formada por estrelas, gás, poeira e outros componentes. A Via Láctea é a galáxia onde está o Sistema Solar."},
{q:"O que causa as fases da Lua?",options:["Mudança no tamanho real da Lua","Mudança na posição entre Sol, Terra e Lua e na parte iluminada que vemos","A Lua produzir luz própria","A atmosfera lunar"],answer:1,level:"medio",explanation:"A Lua reflete a luz do Sol. Conforme a posição relativa entre Sol, Terra e Lua muda, observamos diferentes porções da metade iluminada."},
{q:"O que é um eclipse solar?",options:["A Terra fica entre Sol e Lua","A Lua passa entre a Terra e o Sol e sua sombra atinge parte da Terra","O Sol deixa de emitir luz","Marte cobre o Sol"],answer:1,level:"dificil",explanation:"Um eclipse solar ocorre quando Lua, Terra e Sol ficam alinhados e a Lua passa entre a Terra e o Sol. A sombra lunar atinge apenas determinadas regiões."},
{q:"Como as estrelas produzem grande parte de sua energia?",options:["Combustão comum","Fusão nuclear","Reflexão da luz lunar","Eletricidade atmosférica"],answer:1,level:"medio",explanation:"No interior das estrelas ocorre fusão nuclear. No Sol, núcleos de hidrogênio se combinam para formar hélio e liberar energia."},
{q:"Qual força mantém os planetas em órbita ao redor do Sol?",options:["Magnetismo","Gravidade","Atrito","Eletricidade estática"],answer:1,level:"dificil",explanation:"A gravidade é a atração entre massas. A gravidade do Sol, junto com o movimento dos planetas, mantém suas trajetórias orbitais."},
{q:"Qual planeta é famoso por seus anéis?",options:["Mercúrio","Vênus","Saturno","Marte"],answer:2,level:"dificil",explanation:"Saturno é um gigante gasoso com um sistema de anéis muito evidente. Esses anéis são formados principalmente por partículas de gelo e rocha."},
{q:"O que é um ano-luz?",options:["Uma unidade de tempo","A distância que a luz percorre no vácuo durante um ano","A velocidade da Terra","A distância Terra-Lua"],answer:1,level:"dificil",explanation:"Ano-luz é uma unidade de distância, não de tempo. Ele representa a distância percorrida pela luz no vácuo durante um ano e é útil para medir distâncias astronômicas."}
];