import type { QuizEntry } from "./extendedQuizTypes";
export const quizSociologia: QuizEntry[] = [
{q:"O que a Sociologia estuda principalmente?",options:["Somente fenômenos naturais","As relações e estruturas da vida em sociedade","A composição química dos materiais","O movimento dos planetas"],answer:1,level:"facil",explanation:"A Sociologia estuda a vida social, incluindo relações entre pessoas, grupos e instituições. Ela procura compreender como normas, valores, organizações e processos históricos influenciam a sociedade."},
{q:"O que é cultura em sentido sociológico?",options:["Apenas obras de arte","Conjunto de conhecimentos, valores, costumes e práticas compartilhados socialmente","Somente religião","Apenas educação escolar"],answer:1,level:"facil",explanation:"Cultura inclui conhecimentos, valores, costumes, símbolos, práticas e formas de expressão aprendidas socialmente. Ela é transmitida e transformada ao longo do tempo."},
{q:"O que é socialização?",options:["Um fenômeno exclusivamente biológico","Processo pelo qual as pessoas aprendem normas, valores e formas de convivência","Uma competição esportiva","Uma técnica de pesquisa química"],answer:1,level:"medio",explanation:"Socialização é o processo pelo qual uma pessoa aprende modos de agir, valores, normas e conhecimentos de seu grupo social. Família, escola, amizades e outras instituições participam desse processo."},
{q:"O que é um grupo social?",options:["Um conjunto de pessoas sem qualquer relação","Um conjunto de pessoas que mantém alguma interação ou vínculo social","Somente uma multidão em um estádio","Uma população de animais"],answer:1,level:"medio",explanation:"Grupo social envolve pessoas que mantêm alguma forma de interação, vínculo ou identificação. Uma turma escolar, por exemplo, pode funcionar como grupo social porque seus integrantes compartilham atividades e relações."},
{q:"Desigualdade social significa principalmente:",options:["Que todas as pessoas têm exatamente os mesmos recursos","Diferenças de acesso a recursos, oportunidades e condições de vida","Somente diferenças de idade","Somente diferenças culturais"],answer:1,level:"medio",explanation:"Desigualdade social envolve diferenças na distribuição e no acesso a recursos, direitos, oportunidades e condições de vida. Ela pode aparecer em áreas como renda, educação, moradia e trabalho."},
{q:"O que é cidadania?",options:["Apenas possuir documentos","Participação na vida social e política associada a direitos e deveres","Somente votar","Somente pagar impostos"],answer:1,level:"dificil",explanation:"Cidadania envolve direitos e deveres e a participação na sociedade. Ela pode incluir participação política, acesso a direitos e atuação responsável na comunidade."},
{q:"O que são instituições sociais?",options:["Somente prédios públicos","Estruturas e padrões organizados que orientam relações sociais","Objetos de uso doméstico","Fenômenos naturais"],answer:1,level:"medio",explanation:"Instituições sociais são formas organizadas e relativamente estáveis de orientar comportamentos e relações, como família, escola, Estado e sistemas religiosos. Elas desempenham funções importantes na organização da vida coletiva."},
{q:"O que é mobilidade social?",options:["Movimento de um planeta","Mudança de posição de uma pessoa ou grupo na estrutura social","Mudança de cidade obrigatoriamente","Movimento de uma multidão"],answer:1,level:"dificil",explanation:"Mobilidade social é a mudança de posição de uma pessoa ou grupo dentro da estrutura social. Ela pode ocorrer, por exemplo, quando há mudança de ocupação, renda ou nível educacional."},
{q:"Por que a Sociologia considera importante analisar o contexto social?",options:["Porque comportamentos podem ser influenciados por relações, instituições e condições históricas","Porque toda pessoa pensa exatamente igual","Porque a sociedade não muda","Porque somente a biologia explica a vida social"],answer:0,level:"dificil",explanation:"O contexto social ajuda a compreender como relações, instituições, cultura e condições históricas influenciam comportamentos e oportunidades. Isso não significa que todas as pessoas ajam da mesma maneira, mas que suas experiências acontecem em contextos sociais."},
{q:"O que caracteriza uma mudança social?",options:["A permanência de tudo sem alteração","Transformações relevantes nas relações, instituições ou formas de vida de uma sociedade","Somente uma mudança de clima","Somente uma mudança individual"],answer:1,level:"dificil",explanation:"Mudança social é uma transformação nas formas de organização, relações, instituições ou práticas de uma sociedade. Ela pode acontecer gradualmente ou em períodos de mudanças mais rápidas."}
];