/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as CadernoErrosRouteImport } from './routes/caderno-erros'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as PlanoEstudosRouteImport } from './routes/plano-estudos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as SimuladosRouteImport } from './routes/simulados'
import { Route as MateriasIndexRouteImport } from './routes/materias.index'
import { Route as MateriasSlugRouteImport } from './routes/materias.$slug'
import { Route as AulaSlugYearTopicRouteImport } from './routes/aula.$slug.$year.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CadernoErrosRoute = CadernoErrosRouteImport.update({
  id: '/caderno-erros',
  path: '/caderno-erros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoEstudosRoute = PlanoEstudosRouteImport.update({
  id: '/plano-estudos',
  path: '/plano-estudos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosRoute = SimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasIndexRoute = MateriasIndexRouteImport.update({
  id: '/materias/',
  path: '/materias/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasSlugRoute = MateriasSlugRouteImport.update({
  id: '/materias/$slug',
  path: '/materias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaSlugYearTopicRoute = AulaSlugYearTopicRouteImport.update({
  id: '/aula/$slug/$year/$topic',
  path: '/aula/$slug/$year/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/caderno-erros': typeof CadernoErrosRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/desafios': typeof DesafiosRoute
  '/ferramentas': typeof FerramentasRoute
  '/perfil': typeof PerfilRoute
  '/pesquisa': typeof PesquisaRoute
  '/plano-estudos': typeof PlanoEstudosRoute
  '/planos': typeof PlanosRoute
  '/progresso': typeof ProgressoRoute
  '/quiz': typeof QuizRoute
  '/revisao': typeof RevisaoRoute
  '/simulados': typeof SimuladosRoute
  '/materias/$slug': typeof MateriasSlugRoute
  '/materias/': typeof MateriasIndexRoute
  '/aula/$slug/$year/$topic': typeof AulaSlugYearTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/caderno-erros': typeof CadernoErrosRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/desafios': typeof DesafiosRoute
  '/ferramentas': typeof FerramentasRoute
  '/perfil': typeof PerfilRoute
  '/pesquisa': typeof PesquisaRoute
  '/plano-estudos': typeof PlanoEstudosRoute
  '/planos': typeof PlanosRoute
  '/progresso': typeof ProgressoRoute
  '/quiz': typeof QuizRoute
  '/revisao': typeof RevisaoRoute
  '/simulados': typeof SimuladosRoute
  '/materias/$slug': typeof MateriasSlugRoute
  '/materias': typeof MateriasIndexRoute
  '/aula/$slug/$year/$topic': typeof AulaSlugYearTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/caderno-erros': typeof CadernoErrosRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/desafios': typeof DesafiosRoute
  '/ferramentas': typeof FerramentasRoute
  '/perfil': typeof PerfilRoute
  '/pesquisa': typeof PesquisaRoute
  '/plano-estudos': typeof PlanoEstudosRoute
  '/planos': typeof PlanosRoute
  '/progresso': typeof ProgressoRoute
  '/quiz': typeof QuizRoute
  '/revisao': typeof RevisaoRoute
  '/simulados': typeof SimuladosRoute
  '/materias/$slug': typeof MateriasSlugRoute
  '/materias/': typeof MateriasIndexRoute
  '/aula/$slug/$year/$topic': typeof AulaSlugYearTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/caderno-erros'
    | '/conta'
    | '/dashboard'
    | '/desafios'
    | '/ferramentas'
    | '/perfil'
    | '/pesquisa'
    | '/plano-estudos'
    | '/planos'
    | '/progresso'
    | '/quiz'
    | '/revisao'
    | '/simulados'
    | '/materias/$slug'
    | '/materias/'
    | '/aula/$slug/$year/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/caderno-erros'
    | '/conta'
    | '/dashboard'
    | '/desafios'
    | '/ferramentas'
    | '/perfil'
    | '/pesquisa'
    | '/plano-estudos'
    | '/planos'
    | '/progresso'
    | '/quiz'
    | '/revisao'
    | '/simulados'
    | '/materias/$slug'
    | '/materias'
    | '/aula/$slug/$year/$topic'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/caderno-erros'
    | '/conta'
    | '/dashboard'
    | '/desafios'
    | '/ferramentas'
    | '/perfil'
    | '/pesquisa'
    | '/plano-estudos'
    | '/planos'
    | '/progresso'
    | '/quiz'
    | '/revisao'
    | '/simulados'
    | '/materias/$slug'
    | '/materias/'
    | '/aula/$slug/$year/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  CadernoErrosRoute: typeof CadernoErrosRoute
  ContaRoute: typeof ContaRoute
  DashboardRoute: typeof DashboardRoute
  DesafiosRoute: typeof DesafiosRoute
  FerramentasRoute: typeof FerramentasRoute
  PerfilRoute: typeof PerfilRoute
  PesquisaRoute: typeof PesquisaRoute
  PlanoEstudosRoute: typeof PlanoEstudosRoute
  PlanosRoute: typeof PlanosRoute
  ProgressoRoute: typeof ProgressoRoute
  QuizRoute: typeof QuizRoute
  RevisaoRoute: typeof RevisaoRoute
  SimuladosRoute: typeof SimuladosRoute
  MateriasSlugRoute: typeof MateriasSlugRoute
  MateriasIndexRoute: typeof MateriasIndexRoute
  AulaSlugYearTopicRoute: typeof AulaSlugYearTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caderno-erros': {
      id: '/caderno-erros'
      path: '/caderno-erros'
      fullPath: '/caderno-erros'
      preLoaderRoute: typeof CadernoErrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-estudos': {
      id: '/plano-estudos'
      path: '/plano-estudos'
      fullPath: '/plano-estudos'
      preLoaderRoute: typeof PlanoEstudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados': {
      id: '/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof SimuladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias/': {
      id: '/materias/'
      path: '/materias'
      fullPath: '/materias/'
      preLoaderRoute: typeof MateriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias/$slug': {
      id: '/materias/$slug'
      path: '/materias/$slug'
      fullPath: '/materias/$slug'
      preLoaderRoute: typeof MateriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$slug/$year/$topic': {
      id: '/aula/$slug/$year/$topic'
      path: '/aula/$slug/$year/$topic'
      fullPath: '/aula/$slug/$year/$topic'
      preLoaderRoute: typeof AulaSlugYearTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  CadernoErrosRoute: CadernoErrosRoute,
  ContaRoute: ContaRoute,
  DashboardRoute: DashboardRoute,
  DesafiosRoute: DesafiosRoute,
  FerramentasRoute: FerramentasRoute,
  PerfilRoute: PerfilRoute,
  PesquisaRoute: PesquisaRoute,
  PlanoEstudosRoute: PlanoEstudosRoute,
  PlanosRoute: PlanosRoute,
  ProgressoRoute: ProgressoRoute,
  QuizRoute: QuizRoute,
  RevisaoRoute: RevisaoRoute,
  SimuladosRoute: SimuladosRoute,
  MateriasSlugRoute: MateriasSlugRoute,
  MateriasIndexRoute: MateriasIndexRoute,
  AulaSlugYearTopicRoute: AulaSlugYearTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
