CREATE TABLE public.student_profiles (user_id uuid PRIMARY KEY, name text NOT NULL DEFAULT 'Estudante', school_year text, avatar text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.student_profiles TO authenticated;
GRANT ALL ON public.student_profiles TO service_role;
ALTER TABLE public.student_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students read own profile" ON public.student_profiles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Students create own profile" ON public.student_profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Students edit own profile" ON public.student_profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Students delete own profile" ON public.student_profiles FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE public.student_study_data (user_id uuid PRIMARY KEY, progress jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.student_study_data TO authenticated;
GRANT ALL ON public.student_study_data TO service_role;
ALTER TABLE public.student_study_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students read own study data" ON public.student_study_data FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Students create own study data" ON public.student_study_data FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Students edit own study data" ON public.student_study_data FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Students delete own study data" ON public.student_study_data FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE FUNCTION public.touch_student_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
CREATE TRIGGER touch_student_profiles BEFORE UPDATE ON public.student_profiles FOR EACH ROW EXECUTE FUNCTION public.touch_student_updated_at();
CREATE TRIGGER touch_student_study_data BEFORE UPDATE ON public.student_study_data FOR EACH ROW EXECUTE FUNCTION public.touch_student_updated_at();